apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
    app: {{ template "helper.name" . }}
    chart: {{ template "helper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: {{ template "helper.name" . }}
        release: {{ .Release.Name }}
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      template:
        spec:
          serviceAccountName: {{ template "helper.fullname" . }}
          containers:
          - name: {{ template "helper.fullname" . }}
            image: {{ template "helper.image" . }}
            imagePullPolicy: IfNotPresent
            env:
            - name: ACME_MANAGE_ALL_NAMESPACES
              value: {{ .Values.manageAllNamespaces | quote }}
            - name: ACME_NAMESPACES_WHITELIST
              value: {{ .Values.namespacesWhitelist | quote }}
            - name: ACME_DEMO_ENABLED
              value: {{ .Values.demo.enabled | quote }}
            - name: ACME_DEBUG
              value: {{ .Values.debug | quote }}
            {{- with .Values.env }}
{{ toYaml . | indent 12 }}
            {{- end }}
          restartPolicy: Never
