apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
kind: RoleBinding
metadata:
  name: certs
  namespace: app
subjects:
- kind: ServiceAccount
  name: certs
  namespace: app
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: certs # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io