{{- if .Values.cluster -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "helper.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update" , "create"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "helper.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update" , "create"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["list"]
{{- end -}}